services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - auth-api

  web:
    image: nginx:alpine
    container_name: auth-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - auth-api

  db:
    image: postgres:16
    container_name: auth-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 142728@Mjg
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - auth-api

networks:
  auth-api:
    driver: bridge

volumes:
  pgdata:
